### ISSUE TITLE
Downloads home.component dont work

### ISSUE THREAD

**Issue by semirhadzibulic** [SevenTV/App#1]
tried it with chrome and firefox

**Comment by AnatoleAM** [comment]
Could you provide screenshots or error stacks?

**Comment by semirhadzibulic** [comment]
https://imgur.com/a/UiKi1QD monkaE

**Comment by AnatoleAM** [comment]
Oh- yeah these are cosmetic buttons currently. The chrome extension should be releasing today, faced some issues so it was pushed a few hours.

**Comment by Seanc26** [comment]
Will the firefox extension be released at the same time as chrome?

**Comment by AnatoleAM** [comment]
> Will the firefox extension be released at the same time as chrome?

If it's not too wildly different from chromium's API it should be available this weekend as well, no promises though
