### ISSUE TITLE
TOS + DMCA + Privacy Policy

### ISSUE THREAD

**Issue by TroyDota** [SevenTV/App#2]
You need them or ur gonna get sued into the ground.

**Comment by TroyDota** [comment]
https://www.generateprivacypolicy.com/ <- Privacy Policy

https://www.websitepolicies.com/ <- DMCA + TOS

**Comment by AnatoleAM** [comment]
monkaE true

**Comment by TroyDota** [comment]
I used it cause i made a vod site, https://admiralbulldog.streamervods.live

**Comment by AnatoleAM** [comment]
Legal documents for Terms of Service and Privacy Policy are live.
