### ISSUE TITLE
[Bug] Not able to remove alias

### ISSUE THREAD

**Issue by RANKKY** [SevenTV/App#263]
**Describe the bug**
You're not able to remove an alias after setting one

**To Reproduce**
1. Go to and emote page
2. Click on 'Set alias'

**Expected behavior**
So after removing the emote again and then adding it back the same way, it looks like the original name is used for the emote, but after refreshing the stream chat on twitch, it goes back to the alias. There is no button to remove the alias and the only way is to use the original name but either use an uppercase or lowercase letter.
It's not possible to just set the alias to the original name to "reset/remove the alias"

**Version:**
The version where the bug is occuring is Version: 2.1.4

**Comment by AnatoleAM** [comment]
You can remove all text in the input box then click rename to remove an alias. Please note while this unintuitive, this is designed better on the new website; the current angular app is deprecated and will not receive further updates.
