### ISSUE TITLE
Implement hyperlinks for page elements that redirect to different pages.

### ISSUE THREAD

**Issue by iammac3** [SevenTV/App#4]
Various elements on the frontend of 7tv appear to be designed to function like hyperlinks to different pages.

In the picture below, I have highlighted some elements on the home page that seem to share this property.

![screenie1](https://user-images.githubusercontent.com/81977909/119736478-c44ae780-be4b-11eb-95fd-6a492ab30606.png)

These elements don't have a hyperlink tag to be able to copy a link, e.g. the button that says "emotes" redirects to https://7tv.app/emotes when clicked on but the link cannot be seen when hovering over.

This also holds true for emote elements like image below.
![image](https://user-images.githubusercontent.com/81977909/119736938-813d4400-be4c-11eb-87df-546c62967934.png)

Would be nice to be able to right click and copy a link for an emote rather than having to click on the emote itself and then copy the link from the url bar.

**Comment by talneoran** [comment]
@iammac3 Most of what you described should be added now. Could you try it and see if the issue still exists?

**Comment by iammac3** [comment]
@talneoran Thanks for informing me, it does appear this is now fixed.
